/*
Not Passed The Case? Try One more Time
*/
#include<bits/stdc++.h>
using namespace std;

#define pb          push_back
#define ll          long long
#define str         string
#define vll         vector<long long int>

void solve(){
    ll n,k,x,y,total,red,blue;
    cin>>n>>k>>x>>y;
    
    red = k*x;
    n-=k;
    
    blue = n*y;
    
}


int main(){
    ll t;
    cin>>t;
    while(t--){
        solve();
    }
    
    
    return 0;
}